const db = require('../server/db');
const { User, FavoriteDogs, ViewedPets } = require('../server/db/models');

const users = [
  {
    firstName: 'Teddy',
    lastName: 'Wrotham',
    email: 'twrotham0@ycombinator.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Selle',
    lastName: 'Kamiyama',
    email: 'skamiyama1@bloomberg.com',
    password: '12345',
    googleId: '12345',
    zipcode: '78275-000',
  },
  {
    firstName: 'Jo-ann',
    lastName: 'Thick',
    email: 'jthick2@bloglovin.com',
    password: '12345',
    googleId: '12345',
    zipcode: '4323',
  },
  {
    firstName: 'Meredithe',
    lastName: 'Bleakley',
    email: 'mbleakley3@xing.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Kimberlyn',
    lastName: 'Drysdall',
    email: 'kdrysdall4@mysql.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Shirley',
    lastName: 'Cordero',
    email: 'scordero5@ovh.net',
    password: '12345',
    googleId: '12345',
    zipcode: '168020',
  },
  {
    firstName: 'Alexandro',
    lastName: 'Foran',
    email: 'aforan6@miibeian.gov.cn',
    password: '12345',
    googleId: '12345',
    zipcode: '40524',
  },
  {
    firstName: 'Jorry',
    lastName: 'Figures',
    email: 'jfigures7@example.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Xever',
    lastName: 'Paxforde',
    email: 'xpaxforde8@oakley.com',
    password: '12345',
    googleId: '12345',
    zipcode: '69115-000',
  },
  {
    firstName: 'Lainey',
    lastName: 'Jumeau',
    email: 'ljumeau9@umn.edu',
    password: '12345',
    googleId: '12345',
    zipcode: '21109',
  },
  {
    firstName: 'Basilio',
    lastName: 'Dionisetto',
    email: 'bdionisettoa@mozilla.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Cynthia',
    lastName: 'Americi',
    email: 'camericib@163.com',
    password: '12345',
    googleId: '12345',
    zipcode: '40068',
  },
  {
    firstName: 'Kym',
    lastName: 'Custy',
    email: 'kcustyc@unesco.org',
    password: '12345',
    googleId: '12345',
    zipcode: '3384',
  },
  {
    firstName: 'Phillip',
    lastName: 'Millington',
    email: 'pmillingtond@arizona.edu',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Dulciana',
    lastName: 'Taffley',
    email: 'dtaffleye@newsvine.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Shanda',
    lastName: 'Kilday',
    email: 'skildayf@privacy.gov.au',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Kyrstin',
    lastName: 'Hail',
    email: 'khailg@cam.ac.uk',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Barbra',
    lastName: 'Willmetts',
    email: 'bwillmettsh@pbs.org',
    password: '12345',
    googleId: '12345',
    zipcode: '9023',
  },
  {
    firstName: 'Henrik',
    lastName: 'Sanbrook',
    email: 'hsanbrooki@seattletimes.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Franzen',
    lastName: 'Giblin',
    email: 'fgiblinj@reference.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Kiel',
    lastName: 'Roubottom',
    email: 'kroubottomk@oakley.com',
    password: '12345',
    googleId: '12345',
    zipcode: '241904',
  },
  {
    firstName: 'Suellen',
    lastName: 'Apple',
    email: 'sapplel@surveymonkey.com',
    password: '12345',
    googleId: '12345',
    zipcode: '7000',
  },
  {
    firstName: 'Wood',
    lastName: 'Dunnett',
    email: 'wdunnettm@samsung.com',
    password: '12345',
    googleId: '12345',
    zipcode: 'M1M',
  },
  {
    firstName: 'Prescott',
    lastName: 'Vanyutin',
    email: 'pvanyutinn@qq.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Edythe',
    lastName: 'Medgwick',
    email: 'emedgwicko@hibu.com',
    password: '12345',
    googleId: '12345',
    zipcode: '624287',
  },
  {
    firstName: 'Suzette',
    lastName: 'Follett',
    email: 'sfollettp@wordpress.com',
    password: '12345',
    googleId: '12345',
    zipcode: '8405',
  },
  {
    firstName: 'Paten',
    lastName: 'Paragreen',
    email: 'pparagreenq@jimdo.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Rahel',
    lastName: 'Tythacott',
    email: 'rtythacottr@newsvine.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Perry',
    lastName: 'Valentin',
    email: 'pvalentins@a8.net',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Annnora',
    lastName: 'Stute',
    email: 'astutet@ibm.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Erv',
    lastName: 'Oles',
    email: 'eolesu@indiegogo.com',
    password: '12345',
    googleId: '12345',
    zipcode: '13853 CEDEX 3',
  },
  {
    firstName: 'Minne',
    lastName: 'Elwill',
    email: 'melwillv@ed.gov',
    password: '12345',
    googleId: '12345',
    zipcode: '6417',
  },
  {
    firstName: 'Julie',
    lastName: 'Batrim',
    email: 'jbatrimw@arizona.edu',
    password: '12345',
    googleId: '12345',
    zipcode: '02-983',
  },
  {
    firstName: 'Gavin',
    lastName: 'Garvan',
    email: 'ggarvanx@archive.org',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Allx',
    lastName: 'Goold',
    email: 'agooldy@histats.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Anthea',
    lastName: 'Steventon',
    email: 'asteventonz@umn.edu',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Sally',
    lastName: 'Brozek',
    email: 'sbrozek10@tripadvisor.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Kai',
    lastName: 'Pech',
    email: 'kpech11@loc.gov',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Bartolemo',
    lastName: 'Dochon',
    email: 'bdochon12@canalblog.com',
    password: '12345',
    googleId: '12345',
    zipcode: '663 30',
  },
  {
    firstName: 'Deloria',
    lastName: 'Motion',
    email: 'dmotion13@usda.gov',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Kerrin',
    lastName: 'Phebey',
    email: 'kphebey14@furl.net',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Ruthie',
    lastName: 'Gerrish',
    email: 'rgerrish15@mac.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Abra',
    lastName: 'Bradlaugh',
    email: 'abradlaugh16@1688.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Manya',
    lastName: 'Luxon',
    email: 'mluxon17@state.gov',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Sheff',
    lastName: 'Shepcutt',
    email: 'sshepcutt18@ezinearticles.com',
    password: '12345',
    googleId: '12345',
    zipcode: '416530',
  },
  {
    firstName: 'Rock',
    lastName: 'Clackers',
    email: 'rclackers19@reuters.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Mycah',
    lastName: 'Wilstead',
    email: 'mwilstead1a@microsoft.com',
    password: '12345',
    googleId: '12345',
    zipcode: '9701',
  },
  {
    firstName: 'Audra',
    lastName: 'Philps',
    email: 'aphilps1b@nps.gov',
    password: '12345',
    googleId: '12345',
    zipcode: '245',
  },
  {
    firstName: 'Hyacinth',
    lastName: 'Beebee',
    email: 'hbeebee1c@yahoo.co.jp',
    password: '12345',
    googleId: '12345',
    zipcode: '353642',
  },
  {
    firstName: 'Samara',
    lastName: 'Wiz',
    email: 'swiz1d@springer.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Adrienne',
    lastName: 'Cudihy',
    email: 'acudihy1e@domainmarket.com',
    password: '12345',
    googleId: '12345',
    zipcode: '43666',
  },
  {
    firstName: 'Phil',
    lastName: 'Baseley',
    email: 'pbaseley1f@booking.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Doroteya',
    lastName: 'Odams',
    email: 'dodams1g@jalbum.net',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Ferdie',
    lastName: 'Jotcham',
    email: 'fjotcham1h@wikimedia.org',
    password: '12345',
    googleId: '12345',
    zipcode: '90140',
  },
  {
    firstName: 'Joe',
    lastName: 'Mattei',
    email: 'jmattei1i@comcast.net',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Terri',
    lastName: 'Ryan',
    email: 'tryan1j@wordpress.org',
    password: '12345',
    googleId: '12345',
    zipcode: '77-130',
  },
  {
    firstName: 'Ingamar',
    lastName: 'Cork',
    email: 'icork1k@t.co',
    password: '12345',
    googleId: '12345',
    zipcode: '3830-268',
  },
  {
    firstName: 'Vinnie',
    lastName: 'Wahner',
    email: 'vwahner1l@army.mil',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Danie',
    lastName: 'Weafer',
    email: 'dweafer1m@ask.com',
    password: '12345',
    googleId: '12345',
    zipcode: '1041',
  },
  {
    firstName: 'Tully',
    lastName: 'Thaller',
    email: 'tthaller1n@omniture.com',
    password: '12345',
    googleId: '12345',
    zipcode: '80130',
  },
  {
    firstName: 'Hyacinthia',
    lastName: 'Lightning',
    email: 'hlightning1o@1und1.de',
    password: '12345',
    googleId: '12345',
    zipcode: '3332',
  },
  {
    firstName: 'Kelcy',
    lastName: 'Gratrix',
    email: 'kgratrix1p@csmonitor.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Kirby',
    lastName: 'Britzius',
    email: 'kbritzius1q@barnesandnoble.com',
    password: '12345',
    googleId: '12345',
    zipcode: '3605',
  },
  {
    firstName: 'Shane',
    lastName: 'Haversham',
    email: 'shaversham1r@cmu.edu',
    password: '12345',
    googleId: '12345',
    zipcode: '8200-567',
  },
  {
    firstName: 'Frederich',
    lastName: 'Mennell',
    email: 'fmennell1s@bloomberg.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Yurik',
    lastName: 'Attree',
    email: 'yattree1t@so-net.ne.jp',
    password: '12345',
    googleId: '12345',
    zipcode: '1116',
  },
  {
    firstName: 'Jenda',
    lastName: 'Burl',
    email: 'jburl1u@php.net',
    password: '12345',
    googleId: '12345',
    zipcode: '647462',
  },
  {
    firstName: 'Marietta',
    lastName: 'Lambregts',
    email: 'mlambregts1v@wired.com',
    password: '12345',
    googleId: '12345',
    zipcode: '33901',
  },
  {
    firstName: 'Samuele',
    lastName: 'McPheat',
    email: 'smcpheat1w@ebay.com',
    password: '12345',
    googleId: '12345',
    zipcode: '5035',
  },
  {
    firstName: 'Klement',
    lastName: 'Raddin',
    email: 'kraddin1x@google.nl',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Creighton',
    lastName: 'MacMearty',
    email: 'cmacmearty1y@nydailynews.com',
    password: '12345',
    googleId: '12345',
    zipcode: '2629',
  },
  {
    firstName: 'Jerrilyn',
    lastName: 'Nesfield',
    email: 'jnesfield1z@theatlantic.com',
    password: '12345',
    googleId: '12345',
    zipcode: '999-5313',
  },
  {
    firstName: 'Braden',
    lastName: 'Illesley',
    email: 'billesley20@marriott.com',
    password: '12345',
    googleId: '12345',
    zipcode: '30358',
  },
  {
    firstName: 'Marguerite',
    lastName: 'Danilowicz',
    email: 'mdanilowicz21@ebay.co.uk',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Sydelle',
    lastName: 'Stirley',
    email: 'sstirley22@surveymonkey.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Christie',
    lastName: 'Seamans',
    email: 'cseamans23@cdbaby.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Duky',
    lastName: 'Measey',
    email: 'dmeasey24@elegantthemes.com',
    password: '12345',
    googleId: '12345',
    zipcode: '47214',
  },
  {
    firstName: 'Eryn',
    lastName: 'Donovin',
    email: 'edonovin25@exblog.jp',
    password: '12345',
    googleId: '12345',
    zipcode: '90190',
  },
  {
    firstName: 'Celestia',
    lastName: 'Fortescue',
    email: 'cfortescue26@ft.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Brnaby',
    lastName: 'Longbottom',
    email: 'blongbottom27@livejournal.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Junette',
    lastName: 'Boldison',
    email: 'jboldison28@1und1.de',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Willi',
    lastName: 'Macak',
    email: 'wmacak29@chronoengine.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Tully',
    lastName: 'Guitt',
    email: 'tguitt2a@tiny.cc',
    password: '12345',
    googleId: '12345',
    zipcode: '82-340',
  },
  {
    firstName: 'Cathy',
    lastName: 'Golder',
    email: 'cgolder2b@cnet.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Pebrook',
    lastName: 'Leal',
    email: 'pleal2c@who.int',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Chiquita',
    lastName: 'Steeples',
    email: 'csteeples2d@reuters.com',
    password: '12345',
    googleId: '12345',
    zipcode: '16015 CEDEX',
  },
  {
    firstName: 'Archambault',
    lastName: 'Sposito',
    email: 'asposito2e@amazon.de',
    password: '12345',
    googleId: '12345',
    zipcode: '35920-000',
  },
  {
    firstName: 'Florrie',
    lastName: 'Berens',
    email: 'fberens2f@sogou.com',
    password: '12345',
    googleId: '12345',
    zipcode: '421 62',
  },
  {
    firstName: 'Bernette',
    lastName: 'Caldicott',
    email: 'bcaldicott2g@a8.net',
    password: '12345',
    googleId: '12345',
    zipcode: '84409',
  },
  {
    firstName: 'Brittani',
    lastName: 'Friedenbach',
    email: 'bfriedenbach2h@addtoany.com',
    password: '12345',
    googleId: '12345',
    zipcode: 'L9H',
  },
  {
    firstName: 'Greg',
    lastName: 'McMarquis',
    email: 'gmcmarquis2i@smugmug.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Sarajane',
    lastName: 'Skelhorn',
    email: 'sskelhorn2j@ted.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Zandra',
    lastName: 'Stares',
    email: 'zstares2k@1und1.de',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Flemming',
    lastName: 'Czapla',
    email: 'fczapla2l@psu.edu',
    password: '12345',
    googleId: '12345',
    zipcode: '6128',
  },
  {
    firstName: 'Petronia',
    lastName: 'Greiswood',
    email: 'pgreiswood2m@lulu.com',
    password: '12345',
    googleId: '12345',
    zipcode: '44911 CEDEX 9',
  },
  {
    firstName: 'Dana',
    lastName: 'Myrtle',
    email: 'dmyrtle2n@thetimes.co.uk',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Elaine',
    lastName: "O'Brallaghan",
    email: 'eobrallaghan2o@cloudflare.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Joshua',
    lastName: 'Robshaw',
    email: 'jrobshaw2p@unicef.org',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Lelah',
    lastName: 'Lante',
    email: 'llante2q@google.pl',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
  {
    firstName: 'Luisa',
    lastName: 'Stallwood',
    email: 'lstallwood2r@dropbox.com',
    password: '12345',
    googleId: '12345',
    zipcode: null,
  },
];

async function seed() {
  try {
    await db.sync({ force: true });
    console.log('db synced!');
    await Promise.all(
      users.map(element => {
        return User.create(element);
      })
    );
  } catch (err) {
    console.error(err);
  }
}

async function runSeed() {
  console.log('seeding...');
  try {
    await seed();
  } catch (err) {
    console.error(err);
    process.exitCode = 1;
  } finally {
    console.log('closing db connection');
    await db.close();
    console.log('db connection closed');
  }
}

if (module === require.main) {
  runSeed();
}

// we export the seed function for testing purposes (see `./seed.spec.js`)
module.exports = seed;
